GroKart/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('grokartapp.urls',namespace='grokart')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name='accounts'
urlpatterns=[
    path('myaccount/',views.myaccount,name='myaccount'),
    path('login/',views.login,name='login'),
    path('signup/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
     name="reset_password"),
    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'), 
        name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'), 
     name="password_reset_confirm"),
    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'), 
        name="password_reset_complete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Seller(models.Model):
    name=models.OneToOneField(User,on_delete=models.CASCADE)
    is_seller=models.BooleanField(default=False)
    def __str__(self):
        return self.name.username

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User,auth
from django.contrib import messages
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate
from django.contrib.auth import logout as Logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from grokartapp.models import Product,OrderItem
# Create your views here.
def login(request):
    if request.user.is_authenticated:
       return redirect('home') 
    else:
        if request.method =='POST':
            username=request.POST.get('username')
            password=request.POST.get('password')
            user=auth.authenticate(username=username,password=password)
            if user is not None:
                auth.login(request, user)
                return redirect('/')
            else:
                messages.info(request,'Invalid Credentials')
                return redirect('/accounts/login')
        return render(request,'accounts/login.html')

def register(request):
    if request.user.is_authenticated:
        return redirect('/')
    else:
        if request.method=='POST':
            username=request.POST.get('username')
            email=request.POST.get('email')
            first_name=request.POST.get('firstName')
            last_name=request.POST.get('lastName')
            password=request.POST.get('password')
            vpassword=request.POST.get('vpassword')
            if password==vpassword:
                if User.objects.filter(username=username).exists():
                    messages.info(request,'User already exists')
                    return redirect('/accounts/signup')
                else:
                    user=User.objects.create_user(username=username,email=email,first_name=first_name,last_name=last_name,password=password)
                    user.save()
                    return redirect('/accounts/login')
            else:
                messages.info(request,'Password Mismatch')
                return redirect('/accounts/signup')
        else:
            return render(request,'accounts/signup.html')

@login_required
def logout(request):
    Logout(request)
    return redirect('/')

def myaccount(request):
    user_name=request.user.username
    email=request.user.email
    result_cart=()
    order_query=OrderItem.objects.filter(user=request.user,ordered=True)
    print(order_query)
    for i in order_query:
            product_query=Product.objects.filter(product_name=i.item)
            product_query=product_query[0]
            result_cart+=((i.quantity,product_query.product_name,product_query.product_image,product_query.mrp,product_query.price,product_query.slug),)
    try:
        first_letter=request.user.first_name[0].upper()
    except:
        first_letter=""
    return render(request,'accounts/myaccount.html',{'profile_letter':first_letter,'result_cart':result_cart})

templates/accounts/login.html
{% extends 'index.html' %}
{% block title %}Login | GroKart{% endblock %}
{% block content %}
<div class="login_box">
    <div class="login-form">
        <img src="https://image.freepik.com/free-vector/mobile-login-concept-illustration_114360-135.jpg" alt="">
        <form method="POST" class="login_form">
            {% csrf_token %}
            <h2>Customer Login</h2>
            {% for i in messages %}
            <p>{{i}}</p>
            {% endfor %}
            <div class="login Username">
                <i class="fas fa-user"></i>
                <input type="text" placeholder="Username" name="username">
            </div>
            <div class="login Password">
                <i class="fas fa-lock"></i>
                <input type="password" placeholder="Password" name="password">
            </div>
            <a href="/accounts/reset_password">forgot password?</a>
            <div class="loginbutton">
                <button class="btn btn-success">Login</button>
                <br>
                <br>
                <a href="{% url 'accounts:register' %}">Don't have an account</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/accounts/myaccount.html
{% extends 'index.html' %}
{% block title %}{{user.username}}{% endblock %}
{% block content %}
<div class="account_info">
    <div>
        <div class="account_row">
            <p class='profile p_text'><span>{{profile_letter}}</span></p>
        </div>
        <div class="account_row">
            <p>Username</p>
            <p class='profile p_username'>{{user.username}}</p>
        </div>
        <div class="account_row">
            <p>Name</p>
            <p class='profile p_name'>{{user.first_name}} {{user.last_name}}</p>
        </div>
        <div class="account_row">
            <p>Email</p>
            <p class='profile p_email'>{{user.email}}</p>
        </div>
    </div>
    <div class="order_history">
        <h1>Order History</h1>
        {% for quantity,item,img,mrp,price,slug in result_cart %}
        <div class="mycart_card">
            <img src="/media/{{img}}" alt="">
            <div class="cart-details">
                <p id="item">{{item}}</p>
                <div class="price">
                    <p id='mrp'>&#8377 {{mrp}}</p>
                    <p id='price'>&#8377 {{price}}</p>
                </div>
                
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<style>
    .account_row {
        text-align: left;
        margin: 5px;
    }

    .account_info {
        display: flex;
        flex-direction: column;
    }

    .profile {
        font-size: 20px;
        border-bottom: 1.5px solid rgba(0, 0, 0, 0.1);
    }

    .p_text {
        font-size: 54px;
        margin: 20px 0;
        text-align: center;
        border-bottom: none;
    }

    .p_text span {
        background-color: green;
        padding: 2px 12px;
        border-radius: 100px;
        margin: 0 10px;
    }
</style>
<style>
    .product-details {
        display: flex;
        flex-direction: column;
    }

    

    .mycart_card {
        margin: 10px;
        display: grid;
        grid-template-columns: 0.3fr 1fr;
        box-shadow: 20px 20px 50px rgba(0, 0, 0, 0.5);
        border-radius: 15px;
        background: rgba(255, 255, 255, 0.1);
        overflow: hidden;
        align-items: center;
        border-top: 1px solid rgba(255, 255, 255, 0.5);
        border-left: 1px solid rgba(255, 255, 255, 0.5);
        backdrop-filter: blur(5px);
        padding: 10px;
    }

    .mycart_card img {
        width: 100%;
        padding: 10px;
    }

    .my_cart-div {
        display: grid;
        grid-template-columns: 1fr 0.6fr;
    }

    #item {
        font-size: 24px;
    }

    .price {
        display: flex;
        gap: 10px;
    }

    #mrp {
        text-decoration: line-through;
    }

    .price-details {
        margin: 10px;
        box-shadow: 20px 20px 50px rgba(0, 0, 0, 0.5);
        padding: 12px;
        border-radius: 10px;
        height: 420px;
    }

    .price-details h3 {
        font-weight: 600;
        text-shadow: 2px 2px 2px rgba(0, 0, 0, 0.8);
    }

    #cart-title {
        text-align: center;
        margin: 10px 3px;
        font-weight: 700;
        text-shadow: 2px 2px 2px rgba(0, 0, 0, 0.8);
    }
    .price-details div{
        display:flex;
        justify-content:space-between;
        font-size: 18px;
    }
    .price-details .button{
        font-size:20px;
        text-align:center;
        display:flex;
        justify-content:center;
    }
</style>
{% endblock %}

templates/accounts/password_reset.html
{% extends 'index.html' %}
{% block content %}

<div class="reset-field container" style="padding-top:100px;text-align: center;line-height: 2.4;">
<h1>Reset your Password</h1>
<p>Forgot your password? Please enter your email address and follow the instructions in the email to reset your password</p>
<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" name="Send email" class="btn btn-primary" style='background:#1b8494;width:80px;height:30px;border-radius:20px;cursor: pointer;'>
</form>
</div>

{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'index.html' %}
{% block content %}
<div style="padding-top: 100px; text-align: center;line-height: 2.6;">
    <h1>Password reset complete</h1>
    <p>Your password has been set. You may go ahead and log in now.</p>
    <a href="{% url 'Login' %}"><button style="border: none;background:#1b8494;width: 100px;height: 30px;border-radius:20px;cursor: pointer;">Login</button></a>
</div>
{% endblock %}

templates/accounts/password_reset_form.html
{% extends 'index.html' %}
{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

<div style="padding-top: 100px" class="container">
    <h1>Enter new password</h1>
    <p>Please enter your new password twice so we can verify you typed it in correctly.</p>
<form method='post'>
    {% csrf_token %}
    {{form}}
    <button class='btn btn-primary'>Submit</button>
</form>
</div>
{% endblock %}

templates/accounts/password_reset_sent.html
{% extends 'index.html' %}
{% block content %}
<div style="text-align: center;padding-top: 100px;line-height:2.5;margin-left: 100px;margin-right:100px;">
    <h1>Password Reset sent</h1>
    <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'index.html' %}
{% block title %}Login | GroKart{% endblock %}
{% block content %}
<div class="login_box">
    <div class="login-form">
        <img src="https://image.freepik.com/free-vector/subscriber-concept-illustration_114360-3453.jpg" alt="">
        <form method="POST" class="login_form">
            {%csrf_token %}
            <h2>Customer Sign Up</h2>
            {% for i in messages %}
            {{i}}
            {% endfor %}
            <div class="login Username">
                <i class="fas fa-user"></i>
                <input type="text" placeholder="Username" name="username">
            </div>
            <div class="login firstname">
                <i class="fas fa-user"></i>
                <input type="text" placeholder="First Name" name="firstName">
            </div>
            <div class="login lastname">
                <i class="fas fa-user"></i>
                <input type="text" placeholder="Last Name" name="lastName">
            </div>
            <div class="login email">
                <i class="fas fa-envelope"></i>
                <input type="email" placeholder="Email Address" name="email">
            </div>
            <div class="login Password">
                <i class="fas fa-lock"></i>
                <input type="password" placeholder="Password" name="password">
            </div>
            <div class="login Password">
                <i class="fas fa-lock"></i>
                <input type="password" placeholder="Confirm Password" name="vpassword">
            </div>
            <div class="loginbutton">
                <button class="btn btn-success">Login</button>
                <br>
                <br>
                <a href="{% url 'accounts:login' %}">Have an account?</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}