GroKart/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('grokartapp.urls',namespace='grokart')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
]

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name='accounts'
urlpatterns=[
    path('myaccount/',views.myaccount,name='myaccount'),
    path('login/',views.login,name='login'),
    path('signup/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
     name="reset_password"),
    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'), 
        name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'), 
     name="password_reset_confirm"),
    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'), 
        name="password_reset_complete"),
]

grokartapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'grokartapp'
urlpatterns=[
    path('',views.home,name='home'),
    path('about',views.about,name='about'),
    path('add_product',views.add_product,name='add_product'),
    path('search/',views.search,name='search'),
    path('products/<slug:slug>',views.product_view,name="product_view"),
    path('cart/<slug:slug>/',views.add_to_cart,name='add_to_cart'),
    path('remove-from-cart/<slug:slug>',views.remove_from_cart,name='remove_from_cart'),
    path('mycart/',views.cart,name='cart'),
    path('order_summary/',views.order_summary,name='order_summary'),
    path('thankyou',views.thankyou,name='thankyou'),
    path('customer_support',views.customer_support,name='customer_support')
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Thankyou.html
{% extends 'index.html' %}
{% block title %}Thankyou{% endblock %}
{% block content %}
<img src="https://image.freepik.com/free-vector/online-ordering-food-via-mobile-phone-with-contactless-home-delivery_249405-196.jpg" alt="">
{% endblock %}

templates/aboutus.html
{% extends "index.html" %}
{% block title %}About Us{% endblock %}
{% block content %}
<h1>About Us</h1>
<div class="about container">
    <div class="aboutimage">
        <img src="https://image.freepik.com/free-vector/teamwork-concept-landing-page_52683-20164.jpg" alt="">
    </div>
    <div class="text">
        <p>Grokart is India’s amazing online food and grocery store. With over a huge variety of  products and over a number of  brands, in our website  you will find everything you are looking for. Right from fresh Fruits and Vegetables, Rice and Dals, Spices and Seasonings to Packaged products, Beverages, Personal care products, Meats – we have it all.

            Choose from a wide range of options in every category, exclusively handpicked to help you find the best quality available at the lowest prices. Select a time slot for delivery and your order will be delivered right to your doorstep, anywhere in India. You can pay online using your debit / credit card or by cash / sodexo on delivery.
            
            We guarantee on time delivery, and the best quality! 	</p>
    </div>
</div>
<style>
    h1{
        text-align: center;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        font-size: 3rem;
        margin:30px;
        color: white;
    }
    .about{
        display:grid;
        grid-template-columns: 1fr 1fr;
        align-items:center;
        color: white;
        gap: 20px;
    }
    body{
        background: linear-gradient(rgb(17, 0, 44),rgba(82, 15, 163));
    }
    .about img{
        width: 100%;
        border-radius:100%
    }
</style>
{% endblock %}

templates/add_product.html
{% extends 'index.html' %}
{% block title %}Add Product{% endblock %}
{% block content %}
<h1 id="addtitle">Add Product</h1>
<div class="seller_form">
    <div class="add_image">
        <img src="https://image.freepik.com/free-vector/online-ordering-purchase-making-buying-goods-internet-store-website-female-customer-with-tablet-adding-product-cart-cartoon-character_335657-2561.jpg" alt="add_product_img" id="addProductimg">
    </div>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <select class="form-select" aria-label="Default select example" name="category">
                    <option selected disabled="disabled">Product Category</option>
                    <option value="Fruits and Vegetables">Fruits</option>
                    <option value="Fruits and Vegetables">Vegetables</option>
                    <option value="Bakery items and dairy">Bakery/Bread</option>
                    <option value="Bakery items and dairy">Dairy</option>
                    <option value="Snacks and beverages">Snacks</option>
                    <option value="Snacks and beverages">Beverages</option>
                    <option value="Egg meat and fish">Egg Meat and Fish</option>
                    <option value="Frozen Food">Frozen Food</option>
                    <option value="staples">Staples</option>
                </select>
            </div>
            <div class="mb-3">
                <label for="productName" class="form-label">Product Name</label>
                <input type="text" class="form-control" id="productName" name="productName">
            </div>
            <div class="form-floating">
                <textarea class="form-control" placeholder="Write about product" id="productDescription"
                    style="height: 100px" name="productDescription"></textarea>
                <label for="productDescription">Product Description</label>
            </div>
            <div class="mb-3">
                <label for="mrp" class="form-label">MRP</label>
                <input type="tel" class="form-control" id="mrp" name="mrp">
            </div>
            <div class="mb-3">
                <label for="price" class="form-label">Price</label>
                <input type="tel" class="form-control" id="price" name="price">
            </div>
            <div class="mb-3">
                <label for="slug" class="form-label">Slug</label>
                <input type="text" class="form-control" id="slug" name="slug">
            </div>
            <div class="mb-3">
                <label for="pincodes" class="form-label">Available Pincodes</label>
                <input type="text" class="form-control" id="pincodes" name="pincodes">
            </div>
            <div class="mb-3">
                <label for="stock" class="form-label">Stock</label>
                <input type="text" class="form-control" id="stock" name="stock">
            </div>
            <div>
                <label for="img">Upload Product image:</label>
                <input type="file" id="img" name="product_img" accept="image/*">
            </div>
            <br>

            <button class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>
<style>
    body {
        margin: 0;
        padding: 0;
        background: linear-gradient(rgb(54, 0, 153), rgb(31, 0, 92)) no-repeat;
        background-size: 100% 100%;
        background-position: center;
    }

    .seller_form {
        display: grid;
        grid-template-columns: 1fr 1fr;
        align-items: center;
        gap: 20px;
    }

    #addProductimg {
        width: 100%;
        border-top-right-radius: 100%;
        border-bottom-right-radius: 100%;
    }

    #addtitle {
        text-align: center;
        color: white;
        font-size: 44px;
        padding:10px;
        text-shadow: 2px 2px black;
    }

    label {
        color: white;
    }
    form{
        margin: 10px;
    }
    .form-floating label{
        color: black;
    }
</style>
<script>
    const product_title=document.getElementById("productName");
    const sluginput=document.getElementById("slug");
    const slugify =(val)=>{
        return val.toString().toLowerCase().trim()
        .replace(/&/g,'-and-')
        .replace(/[\s\W-]+/g,'-')
    }

    product_title.addEventListener('keyup',(e)=>{
        sluginput.setAttribute("value",slugify(product_title.value))
    })
</script>
{% endblock %}

templates/cart.html
{% extends "index.html" %}
{% block title %}My Cart {% endblock %}
{% block content %}
<h2 id="cart-title">My Cart ({{n}})</h2>
{% for i in messages %}
{{message}}
{% endfor %}
<div class="my_cart-div">
    <div class="product-details">
        {% for quantity,item,img,mrp,price,slug in result_cart %}
        <div class="mycart_card">
            <img src="/media/{{img}}" alt="">
            <div class="cart-details">
                <p id="item">{{item}}</p>
                <div class="price">
                    <p id='mrp'>&#8377 {{mrp}}</p>
                    <p id='price'>&#8377 {{price}}</p>
                </div>
                <div class="quantity">
                    <p id='quantity'>Quantity: {{quantity}}</p>
                    <div class="quantity-input">
                        <a href="/remove-from-cart/{{slug}}"><i class="fas fa-minus"></i></a>
                        <input type="text" value="{{quantity}}" disabled="true" style="width:30px;text-align:center">
                        <a href="/cart/{{slug}}"><i class="fas fa-plus"></i></a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="price-details">
        <h3>Price Details</h3>
        <hr>
        <div id="total_price">
            <p>Price</p>
            <p>&#8377 {{total_mrp}}</p>
        </div>
        <div id="total_discount">
            <p>Discount</p>
            <p>- &#8377 {{total_discount}}</p>
        </div>
        <div>
            <p>Delivery Charges</p>
            <p>FREE</p>
        </div>
        <hr>
        <div class="total_amount">
            <p>Total Amount</p>
            <p>&#8377 {{total_price}}</p>
        </div>
        <hr>
        <p>You will save &#8377 {{total_discount}} on this order</p>
        <div class="button">
            <a href="/order_summary"><button class="btn-primary">Proceed to checkout</button></a>
        </div>
    </div>
    
</div>
<style>
    .product-details {
        display: flex;
        flex-direction: column;
    }

    body {
        background: linear-gradient(to right, rgb(17, 0, 44), rgb(53, 8, 124));
        color: white;
    }

    .mycart_card {
        margin: 10px;
        display: grid;
        grid-template-columns: 0.3fr 1fr;
        box-shadow: 20px 20px 50px rgba(0, 0, 0, 0.5);
        border-radius: 15px;
        background: rgba(255, 255, 255, 0.1);
        overflow: hidden;
        align-items: center;
        border-top: 1px solid rgba(255, 255, 255, 0.5);
        border-left: 1px solid rgba(255, 255, 255, 0.5);
        backdrop-filter: blur(5px);
        padding: 10px;
    }

    .mycart_card img {
        width: 100%;
        padding: 10px;
    }

    .my_cart-div {
        display: grid;
        grid-template-columns: 1fr 0.6fr;
    }

    #item {
        font-size: 24px;
    }

    .price {
        display: flex;
        gap: 10px;
    }

    #mrp {
        text-decoration: line-through;
    }

    .price-details {
        margin: 10px;
        box-shadow: 20px 20px 50px rgba(0, 0, 0, 0.5);
        padding: 12px;
        border-radius: 10px;
        height: 420px;
    }

    .price-details h3 {
        font-weight: 600;
        text-shadow: 2px 2px 2px rgba(0, 0, 0, 0.8);
    }

    #cart-title {
        text-align: center;
        margin: 10px 3px;
        font-weight: 700;
        text-shadow: 2px 2px 2px rgba(0, 0, 0, 0.8);
    }
    .price-details div{
        display:flex;
        justify-content:space-between;
        font-size: 18px;
    }
    .price-details .button{
        font-size:20px;
        text-align:center;
        display:flex;
        justify-content:center;
    }
</style>
{% endblock %}

templates/footer.html
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
    <!-- Section: Social media -->
    <section
      class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
    >
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->
  
      <!-- Right -->
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-github"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->
  
    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p>
              Here you can use rows and columns to organize your footer content. Lorem ipsum
              dolor sit amet, consectetur adipisicing elit.
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="#!" class="text-reset">Angular</a>
            </p>
            <p>
              <a href="#!" class="text-reset">React</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Vue</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Laravel</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">Pricing</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Settings</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Help</a>
            </p>
          </div>
          <!-- Grid column -->
  
          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  
    <!-- Copyright -->
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright:
      <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

templates/home.html
{% extends 'index.html' %}
{% load static %}
{% block title %} Home {% endblock %}
{% block content %}
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/5.jpeg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/6.jpeg' %}" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/7.jpeg' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  
  <div class="shopbycategory">
    <h2>Shop by Category</h2>
    <div class="category">
      <a href="search/?product=fruits">
        <div class="fruits icon">
          <img src="https://image.freepik.com/free-photo/colorful-fruits-tasty-fresh-ripe-juicy-white-desk_179666-169.jpg" alt="">
          <p>Fruits</p>
        </div>
      </a>
      <a href="search/?product=vegetables">
        <div class="vegetables icon">
          <img src="https://image.freepik.com/free-photo/basket-full-vegetables_1112-316.jpg" alt="">
          <p>Vegetables</p>
        </div>
      </a>
      <a href="search/?product=bakery">
        <div class="bakery icon">
          <img src="https://image.freepik.com/free-photo/delicious-bread-table_144627-12454.jpg" alt="">
          <p>Bakery</p>
        </div>
      </a>
      <a href="search/?product=dairy">
        <div class="dairy icon">
          <img src="https://image.freepik.com/free-vector/natural-milk-products-template_1284-20877.jpg" alt="">
          <p>Dairy</p>
        </div></a>
      <a href="search/?product=snacks">
        <div class="snacks icon">
          <img src="https://images.newindianexpress.com/uploads/user/imagelibrary/2019/9/4/w900X450/Biscuits.jpg" alt="">
          <p>Snacks</p>
        </div>
      </a>
      <div class="beverages icon">
        <img src="https://www.packagingdigest.com/sites/packagingdigest.com/files/styles/article_featured_retina/public/AdobeStock_279692163_Editorial_Use_Only-Beverage-FTR-new.jpg?itok=moSeFM8n" alt="">
        <p>Beverages</p>
      </div>
      <div class="egg icon">
        <img src="https://image.freepik.com/free-photo/three-fresh-organic-raw-eggs-isolated-white-surface_114579-43677.jpg" alt="">
        <p>Egg / Meat / Fish</p>
      </div>
      <div class="frozen icon">
        <img src="https://5.imimg.com/data5/OW/WE/MY-30494656/amul-realmilk-ice-cream-500x500.jpg" alt="">
        <p>Frozen Food</p>
      </div>
      <div class="staples icon">
        <img src="{% static 'images/staples.jpg' %}" alt="">
        <p>Staples</p>
      </div>
    </div>
  </div>
  {% endblock %}
  

templates/index.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %} GroKart | Home {% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<link rel="stylesheet" href="{% static 'css/home.css' %}">

<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background:rgb(17, 0, 44)">
        <div class="container-fluid">
            <a class="navbar-brand" href="/"><img src="{% static 'images/logo.png' %}" alt=""></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item" style="width: 900px;">
                        <form class="d-flex" method="get" action="{% url 'grokartapp:search' %}">
                            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="product">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="/mycart" style="color:white"><i class="fas fa-shopping-cart fa-2x"></i></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a href="/accounts/myaccount"><i class="fas fa-user-circle fa-3x" style="color: #fff"></i></a>
                    </li>
                    <p style="color: #fff;padding-left: 15px;right:0">Welcome {{user.username}}</p>
                    {% else %}
                    {% endif %}
                </ul>
                
                <div>
                    {% if user.is_authenticated %}
                    <a href="{% url 'accounts:logout' %}"><button class="btn btn-primary">Logout</button></a>
                    {% else %}
                    <a href="{% url 'accounts:login' %}"><button class="btn btn-primary">Login</button></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    {% block content %}
    {% endblock %}
    {% block footer %}
<footer class="text-center text-lg-start bg-light text-muted">
    <section
      class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
    >
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <div>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-google"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="fab fa-instagram"></i>
        </a>
      </div>
    </section>
  
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
        
            <h6 class="text-uppercase fw-bold mb-4">
              <img src="{% static 'images/favicon.png' %}" alt="" style="max-width:80px"> GroKart
            </h6>
            <p>
              Here in Gro Kart we have tried our best to provide a good experience to all our customers and sellers , by providing all Groceries and other nutri goods under one platform with an easy accessing and handling feature .
            </p>
          </div>
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              Products
            </h6>
            <p>
              <a href="search/?product=fruits" class="text-reset">Fruits</a>
            </p>
            <p>
              <a href="search/?product=vegetable" class="text-reset">Vegetables</a>
            </p>
            <p>
              <a href="search/?product=dairy" class="text-reset">Dairy</a>
            </p>
            <p>
              <a href="search/?product=snacks" class="text-reset">Snacks</a>
            </p>
          </div>
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            
            <h6 class="text-uppercase fw-bold mb-4">
              Navigate
            </h6>
            
            <p>
              <a href="/about" class="text-reset">About</a>
            </p>
            <p>
              <a href="/account/myaccount" class="text-reset">Orders</a>
            </p>
            <p>
              <a href="/customer_care" class="text-reset">Customer Support</a>
            </p>
        </div>
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase fw-bold mb-4">
              Contact
            </h6>
            <p><i class="fas fa-home me-3"></i> Bangalore, India</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              grokart.info.com
            </p>
            <p><i class="fas fa-phone me-3"></i> phoeneme</p>
            <p><i class="fas fa-print me-3"></i>Phone</p>
          </div>
        </div>
      </div>
    </section>
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2021 Copyright All rights reserved:
      <a class="text-reset fw-bold" href="/">Grokart</a>
    </div>
  </footer>

  {% endblock %}
</body>

</html>

templates/order_summary.html
{% extends "index.html" %}
{% block title %}Order Summary{% endblock %}
{% block content %}
<div class="buyer_form">
    <h1>Fill the Details</h1>{{buyer_address}}
    <form action="" class=buyer_form_form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div>
            <input type="text" placeholder="Full Name" name="name" value="{{user.first_name}} {{user.last_name}}">
        </div>
        <div>
            <input type="text" name="email" id="email" placeholder="Email Address" value="{{user.email}}">
        </div>
        <div class='locality'>
            <input type="text" name="address_one" id="address_one" placeholder="Street Name/Locality"
                value="{{address_one}}">
            <input type="text" name="address_two" id="address_two" placeholder="Area" value={{address_two}}>
            <input type="tel" name='pincode' placeholder="Pincode" id="pincode" value={{pincode}}>
            <input type="text" name="address_three" id="address_three" placeholder="City" value={{address_three}}>
            <input type="text" name="address_four" id="address_four" placeholder="State" value={{address_four}}>
            <input type="text" name="address_five" id="address_five" placeholder="Country" value={{address_five}}>
        </div>
        <div>
            <button>Next</button>
        </div>
    </form>
</div>
<style>
    .buyer_form h1 {
        text-align: center;
    }

    .buyer_form_form {
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        gap: 20px;
        align-items: center;
    }

    .buyer_form_form input {
        border: none;
        border-bottom: 1px solid rgba(0, 0, 0, 0.5);
        border-left: 1px solid rgba(0, 0, 0, 0.5);
        border-radius: 5px;
        font-size: 18px;
        margin: 30px;
        background-color: rgba(0, 0, 0, 0.1);
        padding: 10px;
    }

    .locality {
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        gap: 10px;
    }

    .buyer_form_form button {
        padding: 5px 10px;
        font-size: 25px;
        border-radius: 5px;
        border: none;
        background-color: #009c75;
        margin-bottom: 10px;
    }
</style>
{% endblock %}